/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // SoulfulI Brochure Palette
        "ivory": "#FAF7F2",
        "parchment": "#FFFDFB",
        "lavender": "#F5F1FB",
        "lavender-light": "#EAE1F5",
        "blush": "#FBF1F5",
        "blush-soft": "#F8EDEE",
        "mauve-muted": "#E7DCEE",
        "mauve-brand": "#704F62",
        "charcoal": "#1F1B18",
        "charcoal-muted": "#4E4449",
        "gold-subtle": "#E8E2DA",

        // Existing Stitch Token Aliases
        "inverse-surface": "#352f2c",
        "on-tertiary-fixed-variant": "#5f3c51",
        "on-tertiary-fixed": "#2e1125",
        "primary-fixed": "#ffd8ec",
        "on-surface": "#1f1b18",
        "tertiary-container": "#734d63",
        "on-background": "#1f1b18",
        "surface-container": "#f6ece7",
        "secondary": "#785368",
        "inverse-on-surface": "#f9efe9",
        "on-primary": "#ffffff",
        "secondary-container": "#fdcde5",
        "surface-tint": "#765468",
        "tertiary-fixed": "#ffd8ec",
        "on-secondary-fixed-variant": "#5e3c50",
        "on-secondary-container": "#795468",
        "surface-container-high": "#f0e6e1",
        "on-primary-fixed-variant": "#5c3d50",
        "inverse-primary": "#e5bbd1",
        "surface-container-low": "#fcf2ec",
        "on-secondary-fixed": "#2e1223",
        "outline": "#807479",
        "on-error": "#ffffff",
        "surface-variant": "#ebe0db",
        "surface": "#FAF7F2",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#e8bad1",
        "tertiary": "#59364c",
        "error-container": "#ffdad6",
        "surface-bright": "#FAF7F2",
        "primary-container": "#704f62",
        "primary": "#57384a",
        "outline-variant": "#d1c3c8",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#e9b9d3",
        "background": "#FAF7F2",
        "on-primary-container": "#efc4db",
        "secondary-fixed": "#ffd8eb",
        "on-primary-fixed": "#2c1323",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#f2c2dc",
        "on-surface-variant": "#4e4449",
        "surface-dim": "#e2d8d3",
        "primary-fixed-dim": "#e5bbd1",
        "surface-container-highest": "#ebe0db",
        "on-error-container": "#93000a"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "3xl": "1.75rem",
        full: "9999px"
      },
      spacing: {
        "max-width-reading": "68rem",
        "gutter-mobile": "1.25rem",
        "space-3xl": "4.5rem",
        "gutter-desktop": "3rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "max-width-canvas": "84rem",
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-2xl": "3rem",
        "max-width-prose": "44rem",
        "space-4xl": "6rem"
      },
      fontFamily: {
        serif: ["EB Garamond", "serif"],
        sans: ["Manrope", "sans-serif"],
        "headline-md": ["EB Garamond", "serif"],
        "body-sm": ["Manrope", "sans-serif"],
        "headline-sm": ["EB Garamond", "serif"],
        "display-lg-mobile": ["EB Garamond", "serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "label-md": ["Manrope", "sans-serif"],
        "display-lg": ["EB Garamond", "serif"],
        "label-sm": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "headline-lg": ["EB Garamond", "serif"],
        "headline-lg-mobile": ["EB Garamond", "serif"],
        "body-xl": ["EB Garamond", "serif"]
      },
      fontSize: {
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-sm": ["22px", { lineHeight: "30px", fontWeight: "500" }],
        "display-lg-mobile": ["38px", { lineHeight: "46px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-lg": ["17px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "600" }],
        "display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "500" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.015em", fontWeight: "400" }],
        "headline-lg-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-xl": ["22px", { lineHeight: "34px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
